#!usr/bin/perl

##########################################################
# This program will compare values from the sorted user  
# lists provided by running eblugseparate.pl against the 
# exported values from the EBLUG Drupal profile_value    
# table. With input values named ebsqlodd.txt and        
# ebsqleven.txt, the second and third columns will be    
# compared and produce ebsql_mix.txt. 
# The value (if any) found at the top of this list is the 
# location at where a discrepency can be found in the 
# original export file.
#
# Continue running this program until the ebsql_mix.txt  
# file produces NO results.                              
#                                                        
# Written by Scott DuBois - July 10, 2014                
# Additional help provided by: AppleFritter (PerlMonks)  
########################################################## 

use warnings;
use strict;
use feature qw/say/;

my ($ODD, $EVEN, $MIX);

# Read from files generated by eblugseparate.txt
my $file1 = 'ebsqlodd.txt';
my $file2 = 'ebsqleven.txt';

# Write to this file
my $file3 = '+>ebsql_mix.txt';

# Open files for reading and writing
open ($ODD, $file1)  || die ("Could not open file!");
open ($EVEN, $file2) || die ("Could not open file!");
open ($MIX, $file3)  || die ("Could not open file!");

# Use ebsqlodd.txt as basis for loop iterations
while (my $line1 = <$ODD>)
 {
   my $line2 = <$EVEN>;

   chomp ($line1, $line2);
 
   # Split values read into individual parts
   my ($key1, $num1, $str1) = split (/\s+/, $line1);
   my ($key2, $num2, $str2) = split (/\s+/, $line2);

   # Line-by-line comparison of user number value to
   # find discrepencies
   if ($num1 ne $num2)
     {
        # Un-comment the say values to print to terminal
        #say $line1;
        #say $line2;

        # Print to external file starting at any
        # discrepency point 
        print $MIX "$line1\n";
     }	
 }

# Close all files
close ($ODD)  || die ("Could not close file ebsqlodd.txt!");
close ($EVEN) || die ("Could not close file ebsqleven.txt!");
close ($MIX)  || die ("Could not close file ebsql_mix.txt!");


